SELECT ACCOUNT_ID
FROM [TESTDB].[dbo].[ACCOUNT_AGE_PERFORMANCE]
EXCEPT
SELECT ACCOUNT_ID
FROM [TESTDB].[dbo].[Autodesk_Final]

SELECT ACCOUNT_ID
FROM [TESTDB].[dbo].[Autodesk_Final]
GROUP BY ACCOUNT_ID
EXCEPT
SELECT ACCOUNT_ID
FROM [TESTDB].[dbo].[ACCOUNT_AGE_PERFORMANCE]

SELECT [Customer Size Band],count(distinct ACCOUNT_ID)
FROM [TESTDB].[dbo].[Autodesk_Final]
WHERE ACCOUNT_PERFORMANCE_CATEGORY='Churn'
group by [Customer Size Band]

-- ACCOUNT AGE NOT AVAILABLE

SELECT 
CASE WHEN ACCOUNT_AGE='' THEN 'NA' ELSE 'AVAILABLE' END FLAG,
LEN(ACCOUNT_ID),
COUNT(1)
FROM [TESTDB].[dbo].[Autodesk_Final]
GROUP BY LEN(ACCOUNT_ID),CASE WHEN ACCOUNT_AGE='' THEN 'NA' ELSE 'AVAILABLE' END
ORDER BY 1,2

-- MISSING USAGE DATE (NOT CONTINOUS)

WITH TBL_TEMP AS(
SELECT ACCOUNT_ID,
MIN(CAST([Month] + '-01' AS DATE)) AS MIN_MONTH,
MAX(CAST([Month] + '-01' AS DATE)) AS MAX_MONTH,
COUNT(DISTINCT [Month]) NO_OF_RECORDS
FROM [TESTDB].[dbo].[Autodesk_Final]
GROUP BY ACCOUNT_ID)

SELECT *,
DATEDIFF(MONTH,MIN_MONTH,MAX_MONTH)+1 MONTH_BETWEEN
FROM TBL_TEMP
WHERE (DATEDIFF(MONTH,MIN_MONTH,MAX_MONTH)+1)<>NO_OF_RECORDS

-- PIVOT DATA

WITH TBL_TEMP AS(
SELECT ACCOUNT_ID,MONTH,SEATS_PURCHASED,ACCOUNT_AGE
FROM [TESTDB].[dbo].[Autodesk_Final])
, TBL_FINAL AS(
SELECT *
FROM (
    SELECT 
        ACCOUNT_ID,
		ACCOUNT_AGE,
        [MONTH],
        SEATS_PURCHASED
    FROM TBL_TEMP
) AS SourceTable
PIVOT (
    MAX(SEATS_PURCHASED) 
    FOR [MONTH] IN ([2024-05], [2024-06], [2024-07], [2024-08], [2024-09], [2024-10])
) AS PivotTable)

SELECT *
FROM TBL_FINAL

-- PREVIOUS AND LAST 3 MONTHS AVERAGE MAU

WITH TBL_TEMP AS(
	SELECT *, CAST([Month] + '-01' AS DATE) AS MONTH_START_DATE
	FROM [TESTDB].[dbo].[Autodesk_Final])

SELECT *,
LAG(MAU,1) OVER(PARTITION BY ACCOUNT_ID ORDER BY MONTH_START_DATE) AS PREVIOUS_MAU,
AVG(CAST(MAU AS DECIMAL(10,2))) OVER (PARTITION BY ACCOUNT_ID ORDER BY MONTH_START_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS AvgLast3MonthsMAU
FROM TBL_TEMP

-- ACCOUNT PERFORMANCE FLAG

WITH TBL_MIN_MAX AS(
SELECT ACCOUNT_ID,
MIN(CAST([Month] + '-01' AS DATE)) AS MIN_MONTH,
MAX(CAST([Month] + '-01' AS DATE)) AS MAX_MONTH,
COUNT(DISTINCT [Month]) NO_OF_RECORDS
FROM [TESTDB].[dbo].[Autodesk_Final]
GROUP BY ACCOUNT_ID)
, TBL_CONTINOUS AS(
SELECT *,
DATEDIFF(MONTH,MIN_MONTH,MAX_MONTH)+1 MONTH_BETWEEN,
CASE WHEN (DATEDIFF(MONTH,MIN_MONTH,MAX_MONTH)+1)<>NO_OF_RECORDS THEN 'Not Continous' ELSE 'Continous' END MISSING_FLAG
FROM TBL_MIN_MAX)
, TBL_FINAL AS(
SELECT A.*,MONTH_BETWEEN,NO_OF_RECORDS,MIN_MONTH,MAX_MONTH,
LAG(MAU,1) OVER(PARTITION BY A.ACCOUNT_ID ORDER BY CAST([Month] + '-01' AS DATE)) AS PREVIOUS_MAU,
LEAD(MAU,1) OVER(PARTITION BY A.ACCOUNT_ID ORDER BY CAST([Month] + '-01' AS DATE)) AS NEXT_MAU,
LAG(SEATS_PURCHASED,1) OVER(PARTITION BY A.ACCOUNT_ID ORDER BY CAST([Month] + '-01' AS DATE)) AS PREVIOUS_SEATS_PURCHASED,
LEAD(SEATS_PURCHASED,1) OVER(PARTITION BY A.ACCOUNT_ID ORDER BY CAST([Month] + '-01' AS DATE)) AS NEXT_SEATS_PURCHASED,
MISSING_FLAG
FROM [TESTDB].[dbo].[Autodesk_Final] A
LEFT JOIN TBL_CONTINOUS B ON A.ACCOUNT_ID=B.ACCOUNT_ID)
, TBL_FINAL_FLAGS AS(
SELECT *,
CAST([Month] + '-01' AS DATE) AS MONTH_DATE,
CASE WHEN PREVIOUS_MAU IS NULL AND MISSING_FLAG='Continous' THEN 1 ELSE 0 END NEW_FLAG,
CASE WHEN CAST(SEATS_PURCHASED AS INT)>CAST(PREVIOUS_SEATS_PURCHASED AS INT) AND MISSING_FLAG='Continous' THEN 1 ELSE 0 END EXPANSION_FLAG,
CASE WHEN CAST(PREVIOUS_SEATS_PURCHASED AS INT)>CAST(SEATS_PURCHASED AS INT) AND MISSING_FLAG='Continous' THEN 1 ELSE 0 END CONTRACTION_FLAG,
CASE WHEN NEXT_MAU IS NULL AND MISSING_FLAG='Continous' THEN 1 ELSE 0 END CHURN_FLAG,
CASE WHEN SEATS_PURCHASED=PREVIOUS_SEATS_PURCHASED AND MISSING_FLAG='Continous' THEN 1 ELSE 0 END FLAT_FLAG
FROM TBL_FINAL)

SELECT * 
INTO [TESTDB].[dbo].[Autodesk_Final_Inc_Flags]
FROM TBL_FINAL_FLAGS

-- CHURN ANALYSIS

WITH TBL_TEMP AS(
SELECT *,
MAX(CASE WHEN MONTH_DATE='2024-10-01' THEN 0 ELSE CHURN_FLAG END) OVER(PARTITION BY ACCOUNT_ID) AS FINAL_CHURN_FLAG
FROM [TESTDB].[dbo].[Autodesk_Final_Inc_Flags]
WHERE MONTH_DATE<>'2024-10-01')

SELECT *,
CASE WHEN MONTH_DATE=MAX_MONTH THEN 'CHURN_MONTH'
ELSE 'CHURN_MONTH_'+CAST(DATEDIFF(MONTH,MONTH_DATE,MAX_MONTH) AS VARCHAR)+'M' END CHURN_MONTH_FLAG,
LAG(MAU,1) OVER(PARTITION BY ACCOUNT_ID ORDER BY MONTH_DATE) AS PREVIOUS_MAU,
AVG(CAST(MAU AS DECIMAL(10,2))) OVER (PARTITION BY ACCOUNT_ID ORDER BY MONTH_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS AvgLast3MonthsMAU
FROM TBL_TEMP
WHERE FINAL_CHURN_FLAG=1 --OR ACCOUNT_PERFORMANCE_CATEGORY='Churn'

-- EXPANSION ANALYSIS

WITH TBL_TEMP AS(
SELECT *,
MAX(EXPANSION_FLAG) OVER(PARTITION BY ACCOUNT_ID) AS FINAL_EXPANSION_FLAG,
MAX(CONTRACTION_FLAG) OVER(PARTITION BY ACCOUNT_ID) AS FINAL_CONTRACTION_FLAG
FROM [TESTDB].[dbo].[Autodesk_Final_Inc_Flags])
, TBL_EXPANSION AS(
SELECT ACCOUNT_ID,MAX(MONTH_DATE) AS MAX_EXPANSION_DATE
FROM [TESTDB].[dbo].[Autodesk_Final_Inc_Flags]
WHERE EXPANSION_FLAG=1
GROUP BY ACCOUNT_ID)

SELECT *,
CASE WHEN MONTH_DATE=MAX_EXPANSION_DATE THEN 'EXPANSION_MONTH'
ELSE 'EXPANSION_MONTH_'+CAST(DATEDIFF(MONTH,MAX_EXPANSION_DATE,MONTH_DATE) AS VARCHAR)+'M' END CHURN_MONTH_FLAG,
LAG(MAU,1) OVER(PARTITION BY A.ACCOUNT_ID ORDER BY MONTH_DATE) AS PREVIOUS_MAU,
AVG(CAST(MAU AS DECIMAL(10,2))) OVER (PARTITION BY A.ACCOUNT_ID ORDER BY MONTH_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS AvgLast3MonthsMAU
FROM TBL_TEMP A
LEFT JOIN TBL_EXPANSION B ON A.ACCOUNT_ID=B.ACCOUNT_ID
WHERE FINAL_EXPANSION_FLAG=1 AND FINAL_CONTRACTION_FLAG<>1




WITH TBL_TEMP AS(
SELECT *,
MAX(EXPANSION_FLAG) OVER(PARTITION BY ACCOUNT_ID) AS FINAL_EXPANSION_FLAG,
MAX(CONTRACTION_FLAG) OVER(PARTITION BY ACCOUNT_ID) AS FINAL_CONTRACTION_FLAG
FROM [TESTDB].[dbo].[Autodesk_Final_Inc_Flags])
, TBL_EXPANSION AS(
SELECT ACCOUNT_ID,MAX(MONTH_DATE) AS MAX_EXPANSION_DATE
FROM [TESTDB].[dbo].[Autodesk_Final_Inc_Flags]
WHERE EXPANSION_FLAG=1
GROUP BY ACCOUNT_ID)
, tbl_final as(
SELECT a.*,
CASE WHEN MONTH_DATE=MAX_EXPANSION_DATE THEN 'EXPANSION_MONTH'
ELSE 'EXPANSION_MONTH_'+CAST(DATEDIFF(MONTH,MAX_EXPANSION_DATE,MONTH_DATE) AS VARCHAR)+'M' END CHURN_MONTH_FLAG,
--LAG(MAU,1) OVER(PARTITION BY A.ACCOUNT_ID ORDER BY MONTH_DATE) AS PREVIOUS_MAU,
AVG(CAST(MAU AS DECIMAL(10,2))) OVER (PARTITION BY A.ACCOUNT_ID ORDER BY MONTH_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS AvgLast3MonthsMAU
FROM TBL_TEMP A
LEFT JOIN TBL_EXPANSION B ON A.ACCOUNT_ID=B.ACCOUNT_ID)

select *
from tbl_final
WHERE ACCOUNT_PERFORMANCE_CATEGORY='Expansion' AND FINAL_CONTRACTION_FLAG=1 AND FINAL_EXPANSION_FLAG<>1
--ACCOUNT_ID='5958772509701103823000000'
--[customer size band] = '500+ Seats'
ORDER BY ACCOUNT_ID

select [customer size band],count(distinct ACCOUNT_ID) 
from tbl_final
group by [customer size band]




WITH TBL_TEMP AS(
SELECT *,
MAX(CASE WHEN MONTH_DATE='2024-10-01' THEN 0 ELSE CHURN_FLAG END) OVER(PARTITION BY ACCOUNT_ID) AS FINAL_CHURN_FLAG
FROM [TESTDB].[dbo].[Autodesk_Final_Inc_Flags]
WHERE MONTH_DATE<>'2024-10-01')
, TBL_FINAL AS(
SELECT *,
CASE WHEN MONTH_DATE=MAX_MONTH THEN 'CHURN_MONTH'
ELSE 'CHURN_MONTH_'+CAST(DATEDIFF(MONTH,MONTH_DATE,MAX_MONTH) AS VARCHAR)+'M' END CHURN_MONTH_FLAG,
--LAG(MAU,1) OVER(PARTITION BY ACCOUNT_ID ORDER BY MONTH_DATE) AS PREVIOUS_MAU,
AVG(CAST(MAU AS DECIMAL(10,2))) OVER (PARTITION BY ACCOUNT_ID ORDER BY MONTH_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS AvgLast3MonthsMAU
FROM TBL_TEMP)
--WHERE FINAL_CHURN_FLAG=1 --OR ACCOUNT_PERFORMANCE_CATEGORY='Churn'

SELECT *
FROM TBL_FINAL
WHERE FINAL_CHURN_FLAG<>1 AND ACCOUNT_PERFORMANCE_CATEGORY='Churn'